name: Our GitHub Action Test
on:
  # Schedule visitor count updates (each minute)
  schedule: [{cron: "0 * * * *"}]
  # The lines below allows you to run the workflow manually on ech commit
  # (optional)
  workflow_dispatch:
  push: {branches: ["main"]}

jobs:

  custom_test:
    runs-on: ubuntu-latest
    name: An example workflow as a help file on how to use this GitHub Action
    steps:
      - name: Get page_id
        uses: raelldottin/glitch-me-visitor-count-incrementor@main
        id: page
        with:
          page_id: raelldottin
